# Generated by Django 5.0 on 2026-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoicetemplate_usersactivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='logo_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='logo_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_logo_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business_logo_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
